### ISSUE TITLE
1.1.16 -> 1.1.18 missing \node_modules\node-windows\

### ISSUE THREAD

**Issue by Kompas9** [Ylianst/MeshCentral#5694]
After updating to 1.1.18, this throws an error, and only fix, need to completely reinstall mesh, redownloading node_modules only, it gets deleted when starting the mesh service

C:\MeshCentral\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read properties of null (reading 'send')
    at process.killkid (C:\MeshCentral\node_modules\node-windows\lib\wrapper.js:177:11)
    at process.emit (node:events:518:28)
    at process.exit (node:internal/process/per_thread:192:15)
    at monitor (C:\MeshCentral\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\MeshCentral\node_modules\node-windows\lib\wrapper.js:170:5)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.11.0
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'C:\MeshCentral\node_modules\node-windows\lib\wrapper.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.0
node:internal/modules/cjs/loader:1147
  throw err;

**Comment by si458** [comment]
thank you for reporting!
we had a feeling we might have some issues with the bloody npm packages again!
how did you update? was it automatic? npm install? web ui?
im assuming you run windows? whats the OS? did you install it to begin with using the meshcentral installer?

**Comment by Kompas9** [comment]
Updated via WEB UI (thou after getting it working, it was enough to trip via "serverupdate" command)
Microsoft Windows 10 Pro - 22H2

will post npm list as soon I get access to it

**Comment by si458** [comment]
yeh the webui and 'serverupdate' command are the same thing, so if one trips, the other will trip too...
did you setup meshcentral originally using the meshcentral installer?
or do you have a normal standard node node_modules setup running?

**Comment by Kompas9** [comment]
Yea, MeshCentra setup (2.11). For now it's running 1.1.18, steps:
Completely uninstalled Mesh.
Removed NodeJS 20.11 (without that Mesh setup can't complete installation) 
Re0run Mesh Setup and recovered from backup

**Comment by si458** [comment]
might need to look into the meshcentral installer program,
as not sure WHY you had to uninstall nodejs just to get the installer to do the update?

**Comment by Kompas9** [comment]
Installer hangs on "installing meshcentral service", from what I can tell, at least in that step it never creates "winservice/daemon" folder/file content. 
Mesh setup by default installs Node "v14.17.1"

**Comment by si458** [comment]
side note: in theory if you have it all backup and running now on the latest version 1.1.18
you can stop meshcentral service, uninstall node 14, install node 18/20 (make sure to tick installe xtrac packages and let it do its thing), then start meshcentral service again, and its running on the latest node version!

**Comment by tschettervictor** [comment]
Not sure if this is related, but i couldn’t update to 1.1.18
I had to delete the node_modules folder and reinstall meshcentral to fix it
The server update wouldnt work

**Comment by si458** [comment]
thanks @tschettervictor , whats ur OS? node version? how did you install meshcentral originally?
im trying to build a list of what methods people use so i can TRY and fix the issue properly!
we removed meshcentral installing into itself as it was taking too long,
but i think we might need to go back to install ALL modules in full again?

**Comment by tschettervictor** [comment]
> thanks @tschettervictor whats ur OS? node version? how did you install meshcentral originally? how did you update meshcentral? from what version to what version?
> 
> im trying to build a list of what methods people use so i can TRY and fix the issue properly! I removed meshcentral installing itself into itself as it was taking too long, but i think we might need to go back to installing ALL modules in full again?

FreeBSD
Node 20
I installed via npm install meshcentral

**Comment by si458** [comment]
@tschettervictor so you simply just stopped the meshcentral service, removed the whole node_modules folder, then npm install meshcentral, then started the service again, and it carried on working?

i had a similar weird issue, where when i updated, didnt start up because it complained letsencrypt was missing, but i stopped the servicel, started it again, and it carried on cuz it was infact there!?

npm installs are very weird... even @Ylianst agrees npm installs are being very annoying when you need to install extra packages that arent listed in package.json

**Comment by tschettervictor** [comment]
Correct.

Ive also had it happen where i had to manually start the server again when updating.

**Comment by Raito00** [comment]
Also problem after upgrade to 1.1.18 revert back to 1.1.16

**Comment by si458** [comment]
yes i am aware of this issue, i through i fixed the package install
but i think i made it worse for ANY windows users that uses the meshcentral installer

simple fix at the moment for windows people,
1. backup the whole meshcentral folder, and importantly the meshcentral-data folder !?
2. STOP MESHCENTRAL
3. UNINSTALL MESHCENTRAL COMPLETELY! (including delete folders)
4. UNINSTALL NODEJS (no idea why????)
5. REINSTALL MESHCENTRAL (this will install node 14)
6. STOP MESHCENTRAL AGAIN
7. RESTORE meshcentral-data
8. START MESHCENTRAL
9. check all is ok
CARRY ON IF YOU WANT THE LATEST NODEJS
10. STOP MESHCENTRAL
11. INSTALL NODE 20 (tick box asking for extra packages with chocolatey)
12. START MESHCENTRAL

im in the process of looking into it with my VM why the installer doesnt upgrade correctly?
also how did you upgrade? was it via web ui? was it automatic? did you run the installer and click update?

**Comment by quentinDupont** [comment]
My server is on Ubuntu 20 and I had to follow your steps (and other step, i was a bit lost)
- Stop meshcentral service
- Renaming node_modules to node_module_bak
- Reinstalling nodejs in version 14 : curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - and then sudo apt-get install nodejs (i had to remove nodejs and purge also)
- Verfiy with node -v and npm -v 
- Run npm install meshcentral to get a clean version
- Restart meshcentral to see it works
- stopping meshcentral
- installing node20
- relaunching meshcentral service :tada: 
thanks for this great software !
