### ISSUE TITLE
desktop access broken after updating to 0.6.1 : desktop.m.mouseCursorActive is not a function 

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1676]
After upgrading meshcentral to 0.6.1 desktop access "connect" no longer works (black screen, back to "connect"), in the javascript console I get :

```
Uncaught TypeError: desktop.m.mouseCursorActive is not a function
    connectDesktop https://meshcentral.domain.fr/?viewmode=11&gotonode=cKt0r3pceqoUl4ULVReuTfOEl7Se9NstgZZS4WniGbG5O4EJKxfMgewDnOeFujKn:6620
    onMessage https://meshcentral.domain.fr/?viewmode=11&gotonode=cKt0r3pceqoUl4ULVReuTfOEl7Se9NstgZZS4WniGbG5O4EJKxfMgewDnOeFujKn:2168
    xxOnMessage https://meshcentral.domain.fr/scripts/meshcentral.js:52
meshcentral.domain.fr:6620:31
    connectDesktop https://meshcentral.domain.fr/?viewmode=11&gotonode=cKt0r3pceqoUl4ULVReuTfOEl7Se9NstgZZS4WniGbG5O4EJKxfMgewDnOeFujKn:6620
    onMessage https://meshcentral.domain.fr/?viewmode=11&gotonode=cKt0r3pceqoUl4ULVReuTfOEl7Se9NstgZZS4WniGbG5O4EJKxfMgewDnOeFujKn:2168
    xxOnMessage https://meshcentral.domain.fr/scripts/meshcentral.js:52
function onMessage(server, message)
meshcentral.js:52:10
function onMessage(server, message)
```
meshcentral.js line 52 is

`        if (obj.onMessage) obj.onMessage(obj, message);`

**Comment by guerby** [comment]
If I go back to 0.5.81 (stable) I have no issue with desktop connect.

**Comment by guerby** [comment]
@petervanv I'm trying to connect to a Window 10 machine (waiting on the logging prompt), meshcentral server is installed on a debian 10 machine, auth is LDAP based.

It might be some option in my config.json that changed between versions?

**Comment by petervanv** [comment]
from wich version did you came to version 0.6.1 ? was it very old or recent. Can you connect to the terminal, and does the same issue happens on all your node's or just one ?

**Comment by guerby** [comment]
I can connect through the terminal, issue happens on all nodes. I did not note the previous version, was installed from may 2020 so not that old.

**Comment by guerby** [comment]
Note: would be nice to add the original version in the log message "Starting self upgrade to: 0.5.81"

**Comment by Ylianst** [comment]
Thanks for reporting. Working on this now

**Comment by Ylianst** [comment]
Ok, I am pretty sure I understand the problem. When you updated to 0.6.1, you had a cached version of `agent-desktop-0.0.2.js` that your browser used. The older file does not have this new method. Do you have a reverse proxy that is caching files? In any case, flushing the cache will fix the problem. If I know a bit more about your setup that could be helpful in fixing this in a better way.
