### ISSUE TITLE
Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16

### ISSUE THREAD

**Issue by sysopdm** [Ylianst/MeshCentral#5576]
I got this error in the server log after upgrading from 1.1.15 to 1.1.16.  MeshCentral seems to be running fine.  Any ideas?

I am running MongoDB v3.6.8 for my database.  

Ubuntu 20.04.6 LTS

Node.js v20.9.0

Error Log:

-------- 11/23/2023, 9:59:30 AM ---- 1.1.16 --------

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'mongodb'
Require stack:
- /opt/mc/node_modules/meshcentral/db.js
- /opt/mc/node_modules/meshcentral/meshcentral.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at module.exports.CreateDB (/opt/mc/node_modules/meshcentral/db.js:812:9)
    at CreateMeshCentralServer.obj.StartEx (/opt/mc/node_modules/meshcentral/meshcentral.js:808:28)
    at CreateMeshCentralServer.obj.Start (/opt/mc/node_modules/meshcentral/meshcentral.js:438:66)
    at /opt/mc/node_modules/meshcentral/meshcentral.js:4104:24
    at /opt/mc/node_modules/meshcentral/meshcentral.js:3888:9
    at ChildProcess.exithandler (node:child_process:414:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/mc/node_modules/meshcentral/db.js',
    '/opt/mc/node_modules/meshcentral/meshcentral.js'
  ]
}

-------- 11/23/2023, 9:59:30 AM ---- 1.1.16 --------

Node.js v20.9.0

**Comment by si458** [comment]
how did you upgrade? was it via the web ui or command line or docker image?
did you have node 20 installed while running 1.1.15?
are u running the msehcentral as a service (e.g systemctl start meshcentral) OR manually (node node_modules/meshcentral)
are you running as ROOT or a USER ?

**Comment by sysopdm** [comment]
how did you upgrade? was it via the web ui or command line or docker image? – Web UI
did you have node 20 installed while running 1.1.15? -- Yes
are u running the msehcentral as a service (e.g systemctl start meshcentral) OR manually (node node_modules/meshcentral) -- Service
are you running as ROOT or a USER ? -- ROOT

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 12:27 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

how did you upgrade? was it via the web ui or command line or docker image?
did you have node 20 installed while running 1.1.15?
are u running the msehcentral as a service (e.g systemctl start meshcentral) OR manually (node node_modules/meshcentral)
are you running as ROOT or a USER ?

**Comment by si458** [comment]
is the data inside the mongodb database?

one thing to also check is STOP meshcentral service, then delete the file `mesherrors.txt` inside `meshcentral-data`,
then start the service again and see if the file reappears/data reappears inside it?

im guessing you are seeing this info from `service status meshcentral` ?

**Comment by sysopdm** [comment]
Simon, sorry, not sure what you mean by is this data inside mongodb database?

 

That info was from My Server -> Show server error log

 

Hope that helps and thanks.

 

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 1:38 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

is the data inside the mongodb database?

one thing to also check is STOP meshcentral service, then delete the file mesherrors.txt inside meshcentral-data,
then start the service again and see if the file reappears/data reappears inside it?

im guessing you are seeing this info from service status meshcentral ?

**Comment by si458** [comment]
i mean is the any rows or values or data inside your mongodb server (use like a web ui or gui tool to check)
also try the following:
STOP meshcentral service,
then delete the file mesherrors.txt inside meshcentral-data,
then start the service again
see if the file reappears OR fthe 'show server error log' shows any data

**Comment by sysopdm** [comment]
Nothing in mongodb, file mesherrors.txt does not exist in meshcentral-data directory.

Sorry, wish I had more to offer – strange that I’m the only one having this issue.

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 1:46 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

i mean is the any rows or values or data inside your mongodb server (use like a web ui or gui tool to check)
also try the following:
STOP meshcentral service,
then delete the file mesherrors.txt inside meshcentral-data,
then start the service again
see if the file reappears OR fthe 'show server error log' shows any data

**Comment by si458** [comment]
if you have no data inside your mongodb database/server then meshcentral isnt setup correctly to use mongodb
can you share your `config.json`? (or myserver->show server configuration)

**Comment by sysopdm** [comment]
{

  "$schema": http://info.meshcentral.com/downloads/meshcentral-config-schema.json,

  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",

  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",

  "settings": {

    "cert": "***",

    "WANonly": true,

    "_LANonly": true,

    "_sessionKey": "MyReallySecretPassword1",

    "port": 443,

    "MongoDb": "mongodb://127.0.0.1:27017",

    "_aliasPort": 443,

    "redirPort": 80,

    "_redirAliasPort": 80

  },

  "domains": {

    "": {

      "title": "***",

      "_title2": "***",

      "_minify": true,

      "_newAccounts": true,

      "_userNameIsEmail": true

    }

  },

  "letsencrypt": {

    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",

    "email": ***,

    "names": "***",

    "rsaKeySize": 3072,

    "production": true

  }

}

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 1:56 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

if you have no data inside your mongodb database/server then meshcentral isnt setup correctly to use mongodb
can you share your config.json? (or myserver->show server configuration)

**Comment by si458** [comment]
do you have a `meshcentral.db` file inside `meshcentral-data` ?
also i think you need to set your mongodb to `"mongodb": "mongodb://127.0.0.1:27017/meshcentral"` as you have specified a database name
also you can follow https://ylianst.github.io/MeshCentral/meshcentral/#mongodb-setup to help you setup with mongodb

**Comment by sysopdm** [comment]
Thanks, will give it a try. 

 

DM

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 2:15 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

do you have a meshcentral.db file inside meshcentral-data ?
also i think you need to set your mongodb to "mongodb": "mongodb://127.0.0.1:27017/meshcentral" as you have specified a database name
also you can follow https://ylianst.github.io/MeshCentral/meshcentral/#mongodb-setup to help you setup with mongodb

**Comment by sysopdm** [comment]
Forgot to answer, yes, I do have a meshcentral.db file in meshcentral-data.

 

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 2:15 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

do you have a meshcentral.db file inside meshcentral-data ?
also i think you need to set your mongodb to "mongodb": "mongodb://127.0.0.1:27017/meshcentral" as you have specified a database name
also you can follow https://ylianst.github.io/MeshCentral/meshcentral/#mongodb-setup to help you setup with mongodb

**Comment by sysopdm** [comment]
Ok, so I must be using MongoDB as the last modify date of meshcentral.db was over a year ago when I migrated over to MongoDB:

 

-rw-r--r-- 1 root root   55186 Sep  5  2022 meshcentral.db

 

I looked in my MongoDB directory and see:

 

-rw------- 1 mongodb mongodb    16384 Nov  1 17:50 collection-0-1674910036067663091.wt

-rw------- 1 mongodb mongodb  1712128 Nov 24 19:09 collection-0-595965129421123559.wt

-rw------- 1 mongodb mongodb   147456 Nov 24 19:10 collection-16-595965129421123559.wt

-rw------- 1 mongodb mongodb    40960 Nov  1 17:51 collection-2-1674910036067663091.wt

-rw------- 1 mongodb mongodb   790528 Nov 24 19:10 collection-2-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov 24 19:10 collection-4-1674910036067663091.wt

-rw------- 1 mongodb mongodb 21446656 Nov 24 19:10 collection-8-595965129421123559.wt

drwx------ 2 mongodb mongodb     4096 Nov 24 19:10 diagnostic.data

-rw------- 1 mongodb mongodb    90112 Nov 24 19:10 index-10-595965129421123559.wt

-rw------- 1 mongodb mongodb   180224 Nov 24 19:10 index-11-595965129421123559.wt

-rw------- 1 mongodb mongodb    16384 Nov  1 17:50 index-1-1674910036067663091.wt

-rw------- 1 mongodb mongodb   237568 Nov 24 19:10 index-12-595965129421123559.wt

-rw------- 1 mongodb mongodb   126976 Nov 24 19:10 index-13-595965129421123559.wt

-rw------- 1 mongodb mongodb   315392 Nov 24 19:10 index-14-595965129421123559.wt

-rw------- 1 mongodb mongodb   315392 Nov 24 19:10 index-15-595965129421123559.wt

-rw------- 1 mongodb mongodb   200704 Nov 14 12:50 index-1-595965129421123559.wt

-rw------- 1 mongodb mongodb    45056 Nov 24 19:10 index-17-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov 24 19:10 index-18-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov 24 19:10 index-19-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov  1 17:51 index-3-1674910036067663091.wt

-rw------- 1 mongodb mongodb   577536 Nov 24 19:10 index-3-595965129421123559.wt

-rw------- 1 mongodb mongodb    45056 Nov 14 12:50 index-4-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov 24 18:51 index-5-1674910036067663091.wt

-rw------- 1 mongodb mongodb    16384 Nov  1 17:30 index-5-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov 24 19:10 index-6-1674910036067663091.wt

-rw------- 1 mongodb mongodb    36864 Nov 14 12:50 index-6-595965129421123559.wt

-rw------- 1 mongodb mongodb    36864 Nov  1 17:30 index-7-595965129421123559.wt

-rw------- 1 mongodb mongodb   225280 Nov 24 19:10 index-9-595965129421123559.wt

 

Database files being updated.

 

I’m not sure how to access tables in MongoDB to see data, will need to research that.

 

 

From: Simon Smith ***@***.***>
Reply-To: Ylianst/MeshCentral ***@***.***>
Date: Thursday, November 23, 2023 at 2:15 PM
To: Ylianst/MeshCentral ***@***.***>
Cc: sysopdm ***@***.***>, Author ***@***.***>
Subject: Re: [Ylianst/MeshCentral] Error: Cannot find module 'mongodb' after upgrading from 1.1.15 to 1.1.16 (Issue #5576)

 

do you have a meshcentral.db file inside meshcentral-data ?
also i think you need to set your mongodb to "mongodb": "mongodb://127.0.0.1:27017/meshcentral" as you have specified a database name
also you can follow https://ylianst.github.io/MeshCentral/meshcentral/#mongodb-setup to help you setup with mongodb

**Comment by si458** [comment]
did you resolve this?

**Comment by sysopdm** [comment]
Honestly, I just left well enough alone.  It throws that error still and I did verify that MC is using mongoDB and all appears well.

I’m just hoping nothing breaks when doing future MC updates.

Thanks for checking in though.

DM

**Comment by si458** [comment]
ok no worries, cloising issue then for now
