### ISSUE TITLE
After update to 0.8.59: Error: Cannot find module 'ws'

### ISSUE THREAD

**Issue by evgeniysevost** [Ylianst/MeshCentral#2753]
Hello friends!

I have auto-update enabled to the latest version available ("SelfUpdate": true)
Last night MeshCentral updated to version 0.8.59 and I found this morning that the service was not running. In the log the following text: 

```
-------- 6/10/2021, 12:47:45 AM ---- 0.8.59 --------

node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /meshcentral/node_modules/meshcentral/multiserver.js
- /meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.module.exports.CreateMultiServer (/meshcentral/node_modules/meshcentral/multiserver.js:19:23)
    at RandomBytesJob.<anonymous> (/meshcentral/node_modules/meshcentral/meshcentral.js:1533:63)
    at RandomBytesJob.<anonymous> (node:internal/crypto/random:100:5)
    at RandomBytesJob.onJobDone (node:internal/crypto/random:262:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/meshcentral/node_modules/meshcentral/multiserver.js',
    '/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}
```

I connected to the container and exec:
`npm install ws`
After that the service started and works quite correctly.
 Please check this. Thx!

**Comment by Ylianst** [comment]
Publishing new version now!

**Comment by Ylianst** [comment]
MeshCentral v0.8.60 published. Let me know if that works.

**Comment by elpibedeoro** [comment]
Hi,

Had the same error with manual update on v.0.8.60 but then meshcentral.service restarted by itself and everything works.
