### ISSUE TITLE
After updating to latest version error bad gateway

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#4111]
I just updated to latest version and after it updated "502 Bad Gateway" nginx 1.18.0 Ubuntu. Anyone have updated to the latest version?Thanks.

**Comment by Ylianst** [comment]
Bad gateway indicates that the server NGINX is forwarding to is not responding. This could be because of many things, check that your MeshCentral instance is running.

If you happen to have updated to v1.0.35 and getting this issue because of #4102, add this line to the "settings" section of the config.json:

```
"webPageLengthRandomization": false
```

You can then restart the server and it should work. You can then update to v1.0.36 and remove that line.

**Comment by lexisman** [comment]
I think it was 1.0.36 that I updated not 1.0.35.

**Comment by lexisman** [comment]
Is there a way to downgrade it back first to stable using command line in UBuntu?

**Comment by lexisman** [comment]
This is the error when I tried to manually run the meshcentral with this command,  node ./node_modules/meshcentral:
Error: Cannot find module '/node_modules/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Ylianst** [comment]
Update to MeshCentral v1.0.36, the `readBigUInt64LE is not a function` was fixed. You can also update to the very latest NodeJS v16 or higher and that will also fix that.

**Comment by lexisman** [comment]
Can you please tell me how to do it, "readBigUInt64LE"? Or how to update to the very latest NodeJS version? Thanks.

**Comment by nikitauchaev** [comment]
Ubuntu 20.04, all updates installed, latest nodejs 16 version also here.
Also, I already tried to add "webPageLengthRandomization": false option in config file.
Error same. 

/opt/meshcentral/node_modules/meshcentral/authenticode.js:198
            obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24);
                                                           ^

TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (/opt/meshcentral/node_modules/meshcentral/authenticode.js:198:60)
    at Object.createAuthenticodeHandler (/opt/meshcentral/node_modules/meshcentral/authenticode.js:1289:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:2905:68)
    at Object.CreateMeshCentralServer.obj.StartEx4 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1620:13)
    at Object.CreateMeshCentralServer.obj.StartEx3 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1568:17)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1480:21
    at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:986:43)
    at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1477:35)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/redirserver.js:143:13)
    at Object.onceWrapper (events.js:286:20)


I also try to install other LTS branches of nodejs - same errors

**Comment by lexisman** [comment]
I updated the nodejs manually, since the latest version of nodejs in the repository of ubuntu is only v10. Check the version of your nodejs. After I updated to v16, it works now. Thank you.

**Comment by energywave** [comment]
I'm running on Windows Server 2012, NodeJS ver 11.10.1 (ddn't update that after first installation of MeshCentral, it was never advised to do it).
I have the exact same behavior. I did update MeshCentral to latest version just some minutes ago (didn't remember the version) and MeshCentral stopped working with the following log that keeps repeating in loop (I had to stop the service). So it's not ok on the latest version of Meshcentral...
```
ERR: (node:508) ExperimentalWarning: queueMicrotask() is experimental.
MeshCentral HTTP redirection server running on port 82.
MeshCentral v1.0.36, Hybrid (LAN + WAN) mode, Production mode.
Code signed agent MeshService.exe.
ERR: C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\authenticode.js:198
            obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24);
                                                           ^

TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\authenticode.js:198:60)
    at Object.createAuthenticodeHandler (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\authenticode.js:1289:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:2905:68)
    at Object.CreateMeshCentralServer.obj.StartEx4 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1620:13)
    at Object.CreateMeshCentralServer.obj.StartEx3 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1568:17)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1480:21
    at Object.obj.GetMeshServerCertificate (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\certoperations.js:986:43)
    at CreateMeshCentralServer.obj.StartEx2 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1477:35)
    at Server.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\redirserver.js:143:13)
    at Object.onceWrapper (events.js:285:13)
{ Error: Command failed: C:\Program Files\nodejs\node.exe C:\Program Files\Open Source\MeshCentral\winservice\winservice.js --launch 3080
(node:508) ExperimentalWarning: queueMicrotask() is experimental.
C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\authenticode.js:198
            obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24);
                                                           ^

TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\authenticode.js:198:60)
    at Object.createAuthenticodeHandler (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\authenticode.js:1289:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:2905:68)
    at Object.CreateMeshCentralServer.obj.StartEx4 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1620:13)
    at Object.CreateMeshCentralServer.obj.StartEx3 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1568:17)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1480:21
    at Object.obj.GetMeshServerCertificate (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\certoperations.js:986:43)
    at CreateMeshCentralServer.obj.StartEx2 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1477:35)
    at Server.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\redirserver.js:143:13)
    at Object.onceWrapper (events.js:285:13)

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:202:15)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'C:\\Program Files\\nodejs\\node.exe C:\\Program Files\\Open Source\\MeshCentral\\winservice\\winservice.js --launch 3080' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```
Now I'll try to update NodeJS and report back.
