### ISSUE TITLE
Inernal Server Error

### ISSUE THREAD

**Issue by CSW2000** [Ylianst/MeshCentral#4099]
Hello
This morning my Meschcentral 2 server suddenly stops working 
In the website Online as well as in Local Network I get the message "Internal Server Error"

How do I get the server up and running again?
Who can help me? ,  
I haven't dealt with the topic for a long time.
My system is a Raspi 4 8GB / Linux – System Up to Date 
Linux Version  5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
NPM version 6.14.12
Node Version  10.24.1
Meshcentral Verion ?  Beta Auto update
Greeting Roland W. from Germany

**Comment by nikitauchaev** [comment]
The same situation is on my installation.
Manually updated to the latest available version.
The update rolled in yesterday without any problems.
Today I got a similar picture.

**Comment by CSW2000** [comment]
Hello 
Thanks for the reply
Since I haven't dealt with the MC server for a long time, I don't know how to do a manual update in the server console, just copy over it and if so which folders or components ? , Is there a manual update guide?
Have the MC also connected to a MariaDB, for me as a non-programmer this is always not quite understandable and easy.  
And the whole thing is always a MobaXterm in the console on the RASPI 
HELP!

**Comment by paolor1965** [comment]
Hello
after updating  to version 1.0.34  ( if i reinstall previous version is ok)

-------- 6/9/2022, 10:00:32 AM ---- 1.0.34 --------

TypeError: parent.crypto.randomInt is not a function
    at getRenderArgs (/srv/meshcentral/node_modules/meshcentral/webserver.js:7701:116)
    at handleRootRequestLogin (/srv/meshcentral/node_modules/meshcentral/webserver.js:3045:13)
    at handleRootRequestEx (/srv/meshcentral/node_modules/meshcentral/webserver.js:2901:13)
    at handleRootRequest (/srv/meshcentral/node_modules/meshcentral/webserver.js:2604:13)
    at Layer.handle [as handle_request] (/srv/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/srv/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/srv/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /srv/meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/srv/meshcentral/node_modules/express/lib/router/index.js:335:12)

**Comment by paolor1965** [comment]
node ./node_modules/meshcentral --debug
ERR: /srv/meshcentral/node_modules/meshcentral/meshcentral.js:2245
                if (usergrp.links != null) { for (var j in usergrp.links) { if (j.startsWith('user/') && (users.indexOf(j) < 0)) { users.push(j); } } }
                            ^

TypeError: Cannot read property 'links' of undefined
    at Object.CreateMeshCentralServer.obj.NotifyUserOfDeviceStateChange (/srv/meshcentral/node_modules/meshcentral/meshcentral.js:2245:29)
    at Object.CreateMeshCentralServer.obj.SetConnectivityState (/srv/meshcentral/node_modules/meshcentral/meshcentral.js:2337:21)
    at obj.changeConnectState (/srv/meshcentral/node_modules/meshcentral/amtscanner.js:303:28)
    at Object.obj.parseRmcpPacket (/srv/meshcentral/node_modules/meshcentral/amtscanner.js:283:43)
    at Socket.server.on (/srv/meshcentral/node_modules/meshcentral/amtscanner.js:241:57)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
{ Error: Command failed: /usr/bin/node /srv/meshcentral/node_modules/meshcentral --debug --launch 4979
/srv/meshcentral/node_modules/meshcentral/meshcentral.js:2245
                if (usergrp.links != null) { for (var j in usergrp.links) { if (j.startsWith('user/') && (users.indexOf(j) < 0)) { users.push(j); } } }
                            ^

**Comment by paolor1965** [comment]
after updating node 10 to 14 meshcentral 1.0.34 works

**Comment by CSW2000** [comment]
Thank You paolor1965  my Server is now Running after Upodate Node with linux Command 
`
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs `
  
good work

**Comment by mpleite** [comment]
i had a diferent error:
TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (/home/timesten/node_modules/meshcentral/authenticode.js:198:60)

but afeter @paolor1965 sugestion (upgrade node js from 10.x to 14.x got it fixed!

**Comment by mpleite** [comment]
> I did the update to 14.x but now I just don't get any error here: /home/meshcentral/meshcentral-data/mesherrors.txt
> 
> still the webpage won't show and when I check the service status I see that it smh restarts every 10 seconds...
> 
> so I had to combine it with ""webPageLengthRandomization": false"

Did you upgrade MeshCentral? i did (npn install meshcentral)

**Comment by theoneandonly-vector** [comment]
> > I did the update to 14.x but now I just don't get any error here: /home/meshcentral/meshcentral-data/mesherrors.txt
> > still the webpage won't show and when I check the service status I see that it smh restarts every 10 seconds...
> > so I had to combine it with ""webPageLengthRandomization": false"
> 
> Did you upgrade MeshCentral? i did (npn install meshcentral)

autoupdate did update it

**Comment by mpleite** [comment]
mine too (and thats why stoped working), but then there was a new update online (updated a single file, IIRC). Or you have a diferent issue..

**Comment by theoneandonly-vector** [comment]
> mine too (and thats why stoped working), but then there was a new update online (updated a single file, IIRC). Or you have a diferent issue..

sadly manually running this doesnt fix it without the addition of ""webPageLengthRandomization": false"

**Comment by MDanihy** [comment]
Not working here as well.  Running on Raspberry Pi.  Any fixes mentioned here are not working...

**Comment by Ylianst** [comment]
Just published v1.0.36 with a fix for this. Also, a workaround it to add:

```
"webPageLengthRandomization": false
```

In the settings section of the config.json. You can then update and remove that line.

**Comment by MDanihy** [comment]
How would I update after this change?  Once I reboot I do not get a web interface at all now.

I believe 1.0.36 is the update I went to when this happened.  I only upgraded about 20 minutes ago.

**Comment by Ylianst** [comment]
Put in the work around in the config.json and restart the server. The site will show up again and you can update. After the update you can remove the workaround.

The workaround is to add this line in the settings section of the config.json

```
"webPageLengthRandomization": false
```

Another option is to update to NodeJS v16 or higher, in that case, the server will work fine.

**Comment by MDanihy** [comment]
I did reboot, the site never came back up.  I believe all the attempts to fix prior to your message has totally borked my install.

**Comment by Ylianst** [comment]
Did you add the line in the config.json?

**Comment by MDanihy** [comment]
I can see the devices updating and reconnecting now.

**Comment by Ylianst** [comment]
If you see any errors in "meshcentral-data/mesherrors.txt", send them over.

**Comment by MDanihy** [comment]
No errors since getting it running.  Last logged were from about 30 minutes ago when the issue started.  Thanks again for your help....

**Comment by BillBardon** [comment]
Woke up to this problem this morning. Reading through the comments here, I have updated nodejs to 16.15.1, added the webPageLengthRandomization line, tried downgrading meshcentral, nothing works still have an "unable to connect" browser error, and netstat shows nothing listening on 80 or 443. I would try reinstalling but I have scores of agents and don't want to lose connectivity with them. If I reinstall, what certs/keys do I need to preserve to maintain my connection with deployed agents?

**Comment by mpleite** [comment]
> Woke up to this problem this morning. Reading through the comments here, I have updated nodejs to 16.15.1, added the webPageLengthRandomization line, tried downgrading meshcentral, nothing works still have an "unable to connect" browser error, and netstat shows nothing listening on 80 or 443. I would try reinstalling but I have scores of agents and don't want to lose connectivity with them. If I reinstall, what certs/keys do I need to preserve to maintain my connection with deployed agents?

see https://github.com/Ylianst/MeshCentral/issues/2093#issuecomment-748411880

**Comment by BillBardon** [comment]
Thanks. Followed those steps with same results. I'm suspicious there's something else going on. Would nuke that server and spin up a new one, but the MAC address will change, which will mess up the server id, correct?

**Comment by BillBardon** [comment]
Found [this reddit post](https://www.reddit.com/r/MeshCentral/comments/ufw977/new_meshcentral_server_do_i_need_to_reinstall/) that clears the matter up.

**Comment by Ylianst** [comment]
Ok, will close since this is likely solved. Please feel free to re-open if needed.

**Comment by theoneandonly-vector** [comment]
why is 
"""webPageLengthRandomization": false""
needed when I use nodejs 16?
