### ISSUE TITLE
TypeError after updating to 1.1.55

### ISSUE THREAD

**Issue by roborobs1023** [Ylianst/MeshCentral#7529]
**Describe the bug**

-------- 1/2/2026, 3:31:21 PM ---- 1.1.55 --------

/opt/meshcentral/node_modules/meshcentral/webserver.js:9585
        xargs.title2 = obj.common.replacePlaceholders(xargs.title2, { 
                                  ^

TypeError: obj.common.replacePlaceholders is not a function
    at getRenderArgs (/opt/meshcentral/node_modules/meshcentral/webserver.js:9585:35)
    at dbGetFunc (/opt/meshcentral/node_modules/meshcentral/webserver.js:3236:104)
    at /opt/meshcentral/node_modules/meshcentral/db.js:3002:25
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu
 - Virtualization: [e.g. Docker] Docker

 - Version: [e.g. 1.0.43] 1.1.55
 - Node: [e.g. 18.4.0] Node.js v20.9.0

**Your sanitized config.json file**  
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.tuckeritsolutions.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "<session-key>",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "false",
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": "",
      "keepLastDaysBackup": "",
      "zippassword": ""
    }
  },
  "domains": {
        "": {
        "title": "Tucker IT Solutions",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "false",
        "_userNameIsEmail": true,
    "certUrl": "https://mesh.tuckeritsolutions.com:443"
        }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  }
}

**Comment by si458** [comment]
you have a faulty setup of meshcentral, that line was changed 7 months ago,
and we would of been made aware by now if this was broken

now you are using docker so which docker image are you using as you dont say?
make sure you are using our image `ghcr.io/ylianst/meshcentral:latest` or `ghcr.io/ylianst/meshcentral:1.1.55`

**Comment by si458** [comment]
@roborobs1023 is this still an issue?
