### ISSUE TITLE
Error after upgrade to 0.9.19

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#3103]
Hello,
Just upgraded from 0.8.9.8 to 0.9.19 and this shows in the logs:
```
internal/modules/cjs/loader.js:336
      throw err;
      ^

Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.module.exports.CreateDB (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:646:9)
    at Object.CreateMeshCentralServer.obj.StartEx (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:755:28)
    at Object.CreateMeshCentralServer.obj.Start (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:428:66)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:3316:24 {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Program Files\\Open Source\\MeshCentral\\node_modules\\mongodb\\package.json',
  requestPath: 'mongodb'
}
```

**Comment by nzalev** [comment]
What version of NodeJS are you running?

**Comment by Ylianst** [comment]
Looks like the update did not work well as intended. Do tell what version of NodeJS you are using and before doing anything, make sure you have an off-site backup of the "meshcentral-data" folder.

Once you got your backup. For to the folder above "meshcentral-data" with the command prompt. Check you have sufficient space in the drive. Then rename "node_modules" to "node_modules_bak" and run "npm install meshcentral". That will re-download the "node_modules" folder. Once done, run "node node_modules/meshcentral". The server should install any optional modules and start up again.

Once the server starts up manually correctly, you can CTRL-C to stop it and start it up again using systemd. You can install/uninstall using "node node_modules/meshcentral --help" to see the install and uninstall commands.

Let me know if that helps.

**Comment by MordyT** [comment]
Looks like node 14.3
35GB free space

Server is running, do I really need to uninstall/reinstall?

**Comment by nzalev** [comment]
MongoDB had its version pinned, so it's entirely possible that meshcentral already re-installed the module on its own when it did its module loading. You can try restarting the meshcentral service and see if it produces the error a second time.

If it does produce this error a second time, you can move the `mongodb` folder out of `node_modules` and restart meshcentral. It should re-install MongoDB on its own.

**Comment by nzalev** [comment]
That error occurs when meshcentral tries importing the MongoDB client, but can't find it. If the error is not occurring then there's no longer an issue.

**Comment by Ylianst** [comment]
@nzalev is exactly right. If your server is running correctly, and this was just a one time error, your fine. Just carry on.

**Comment by MordyT** [comment]
Perfect, thanks!
